# Autoregressive NSKT forecasting evaluation for FLEXForecast.
data_name: forecasting_nskt
model: FLEXForecast
flex_model_size: small
flex_mlp_ratio: 2
use_scalar_film: true
use_spatial_cond: true
spatial_cond_scales: [32, 16]
spatial_cond_mode: gated
reynolds_normalization_scale: 40000.0
forecast_baseline: persistence
optimizer: adam
epochs: 100 #300 # 500
learning_rate: 1.0e-4
batch_size: 12
patch_size: 256
stride: 32
scratch_dir: /global/cfs/cdirs/m4633/foundationmodel/nskt_tensor/
prediction_type: v
sampler: ddim
time_steps: 3
total_interp_steps_train: 1
forecast_train_horizon: 1
forecast_conditioning_mode: forecast
forecast_horizon: 20
re_id: -1
checkpoint_path: /pscratch/sd/p/puren93/puren/Interp-DM/checkpoints/checkpoint_Model_ft_FLEXForecast_ReNorm40000_small_mlp2_Data_forecasting_nskt_Optim_adam_cosine_lr0.0001_epoch100_patchsize256_stride32_oneStepForecast_best.pt
# checkpoints/checkpoint_Model_ft_FLEXForecast_ReNorm40000_small_mlp2_Data_forecasting_nskt_Optim_adam_cosine_lr0.0001_epoch500_patchsize256_stride32_oneStepForecast_best.pt
