# Config for: python train.py --config config/ablation/flex_residual_nskt.yaml
run_name: FLEX_residual_nskt_zero
data_name: nskt
model: FLEXResidualZero
flex_model_size: small
flex_mlp_ratio: 2
use_scalar_film: true
use_spatial_cond: true
spatial_cond_scales: [32, 16]
spatial_cond_mode: gated
ddp_find_unused_parameters: true
sampling_freq: 10
validation_freq: 5
optimizer: adam
epochs: 150 # 300
batch_size: 12
learning_rate: 1.0e-4
checkpoint_path: ''
total_interp_steps_train: 20
is_T_fixed: True # false
patch_size: 256
stride: 32
scratch_dir: /global/cfs/cdirs/m4633/foundationmodel/nskt_tensor/
prediction_type: v
sampler: ddim
time_steps: 3
base_width: 128
